# AUTOGENERATED! DO NOT EDIT! File to edit: Untitled.ipynb.

# %% auto #0
__all__ = ['learn', 'cat', 'classifier']

# %% Untitled.ipynb #46a0af79-2f85-4ad3-a0f3-b5f41a88d055
from fastai.vision.all import *
from pathlib import Path
import pathlib
import gradio as gr

if pathlib.Path is pathlib.PosixPath:
    pathlib.WindowsPath = pathlib.PosixPath

# %% Untitled.ipynb #496dee1f-3d64-443c-9a2c-646230d447db
learn = load_learner('banana_disease_model.pkl')

# %% Untitled.ipynb #11b2b61d-5c2c-4bbc-9905-82710cd483d5
cat = ('Corodona','healthy','pestalotiopsis','sigatoka')
def classifier(img):
    pred,idx,probs=learn.predict(img)
    return dict(zip(cat,map(float,probs)))

# %% Untitled.ipynb #f1c040e3-c4d1-4ce4-b4ad-4619c3eee12e
gr.Interface(fn=classifier,inputs='image',outputs= 'label',examples=['sigatoka.webp','healthy.webp','pestalotiopsis.jpeg','corodona.jpeg'],cache_examples=False).launch(allowed_paths=['.'])